### ISSUE TITLE
0.9.2 release

### ISSUE THREAD

**Issue by ghorn** [eclipse-cyclonedds/cyclonedds-python#104]
There have been a few changes that we're interested in. Are there plans for a 0.9.2 release? Thanks!

**Comment by matte1** [comment]
Bump! Would love to have a new release.

**Comment by matte1** [comment]
Also thoughts on weekly prebuilt binary?

**Comment by matte1** [comment]
Yeah I think that would work for us!

**Comment by ghorn** [comment]
A nightly stream would be perfect. Unfortunately we can't build from source with our bazel build system, so this is the only way we can use code between releases.

Would you be able to make it clear which `cyclonedds` and `cyclonedds-cxx` commits the nightly release was built against?

**Comment by ghorn** [comment]
What can we do to help make the nightly stream happen?

**Comment by thijsmie** [comment]
I think I have it, soon coming to a PyPi near you: https://github.com/eclipse-cyclonedds/cyclonedds-python/pull/117

**Comment by matte1** [comment]
❤️❤️❤️

**Comment by ghorn** [comment]
Amazing! We were able to update to the nightly release, including the C/C++ libraries! Thank you!

**Comment by thijsmie** [comment]
Nightly release pipeline ran fine today, seems to be all working now! Closing this if you don't mind 😄
