### ISSUE TITLE
support different DDS namespace hierarchy than directory structure

### ISSUE THREAD

**Issue by ghorn** [eclipse-cyclonedds/cyclonedds-python#106]
I have some repo-specific constraints that cause an issue with the way python code is generated.

Consider this desired project layout:
```
path_a/
path_a/messages_a.idl
path_a/messages_a.hpp  # idlc-generated messages
path_a/messages_a.py  # idlc-generated messages
path_b/
path_b/messages_b.idl
path_b/messages_b.hpp  # idlc-generated messages
path_b/messages_b.py  # idlc-generated messages
```
with these IDLs:
```c++
//  path_a/messages_a.idl
module a_foo {
  struct A_FooStruct {
    float dummy;
  };
};

module a_bar {
  struct A_BarStruct {
    float dummy;
  };
};
```
```c++
//  path_b/messages_b.idl

#include "path_a/messages_a.idl"  // B depends on A

module b_yolo {
  struct B_OtherStruct {
    ::a_foo::A_FooStruct foo_struct;
    ::a_bar::A_BarStruct bar_struct;
  };
};
```
The C++ IDLC generator generates code as I would hope for that project layout. However, the python generator wants to generate this code:

For `messages_a.idl`
```
a_foo/a_foo.py
a_bar/a_bar.py
```
and for `messages_b.idl`
```
b_yolo/b_yolo.py
```

The problem is that the IDL module namespace currently is the same as the python directory structure. This seems to be a pretty deep assumption in the way the generated structs work. Is it technically possible to remove this assumption, so that my python and C++ messages can have the same hierarchy?

My current workaround is to require that modules in the IDL definitions be the same as the location of each IDL file, which causes some long namespaces in C++, difficulty moving things around, etc.

**Comment by thijsmie** [comment]
Hi @ghorn,

While technically possible to make it output things in a different structure, in any case it is going to cause huge headaches. In python there is no such thing as `namespace foo {}` like in C++, the only thing you have are modules. To avoid name collisions you either dump everything in one file and prefix the namespace or you output it like I chose to do. The one file approach is problematic when working with multiple IDL input files: referencing the correct type in python with cross-idl-file references is a headscratcher. In the end keeping the structure of IDL the same in Python is a very conscious choice to maintain the correctness of the output.

What I recommend that you do is use the `py-root-prefix` cli option to nest your generated modules under a parent module. Then run `idlc -l py` on all your files from the same working directory and you have a guaranteed importable python module with correct referencing.

If you must keep the structure the same as c++ with a single file output you will have to take the output of `idlc -l py` and turn it into a installable python package with a `setup.cfg` and then zip it. That'll be ugly in version control but it is a single file with everything in it.

**Comment by ghorn** [comment]
I understand, and this makes sense. Thanks for the information.
