### ISSUE TITLE
Python binding with security features

### ISSUE THREAD

**Issue by JesseRengers** [eclipse-cyclonedds/cyclonedds-python#116]
Hi, I have a problem with using the python binding and security functions.
I build Cyclonedds-python from source via git in the way it is described in the readme. After this, the security libraries are available in `/cyclonedds/install/lib/`. This seems to function well if I use the pubsub tool, i.e.

1. open two terminals
2. point `CYCLONEDDS_URI` to a config file that has one of the security modes configured, for example rtps-sign, in both terminals. I have produced all files that it needs, i.e. permissions and governance files, key materials, certificates with help from https://github.com/eclipse-cyclonedds/cyclonedds/blob/840d802a4e400917e8edc33810eade1bdde44a6d/examples/perfscript/perftest
3. use pubsub --topic hello in both terminals
4. Now I can send messages back and forth between the terminals and if I look at the network traffic I see signed rtps traffic. 

Another sanity check is to use ddsperf, this also generates signed rtps traffic.

However, when I use my own little script and use one of the security modes it fails. I think because the publisher is not matched with a subscriber.

This is a test script that I used. It functions well with no security in place.
**Writer**
```
from dataclasses import dataclass
from cyclonedds.domain import DomainParticipant
from cyclonedds.pub import DataWriter
from cyclonedds.topic import Topic
from cyclonedds.idl import IdlStruct

@dataclass
class Sample(IdlStruct):
        id: int

dp = DomainParticipant()

topic = Topic(dp, "TestTopic", Sample)

dw = DataWriter(dp, topic)

for i in range(342):
        dw.write(Sample(id=(i)))
```
**Reader**
```
from dataclasses import dataclass
from cyclonedds.domain import DomainParticipant
from cyclonedds.sub import DataReader
from cyclonedds.topic import Topic
from cyclonedds.idl import IdlStruct
from cyclonedds.util import duration

@dataclass
class Sample(IdlStruct):
        id: int

dp = DomainParticipant()

topic = Topic(dp, "TestTopic", Sample)

dr = DataReader(dp,topic)

for sample in dr.take_iter(timeout=duration(minutes=1)):
    print(sample)
```

Now I'm not sure if I have to change the code to something that is aware of the security configuration or there is something else going on. Thanks for help in advance!

**Comment by thijsmie** [comment]
Hi @JesseRengers,

I've replicated your setup by setting up security like described in perftest and making sure `CYCLONEDDS_URI` is set and running your two scripts. It seems to be working fine when I add one more thing to the write loop, a `sleep(0.5)`. What I think happens is you start writing samples before connection is established between reader and writer, the delay being just a tiny bit bigger with security involved. By slowing the writer a tiny bit (or wait for a subscription_matched) samples arrive as expected.

Let me know if that also fixes things for you.

**Comment by JesseRengers** [comment]
Thank you @thijsmie, I think this was indeed the problem! Adding a small delay in between the creation of the writer and the actual writing helped.
