### ISSUE TITLE
Can't fetch typeobject when running `cyclonedds typeof` (and similar commands)

### ISSUE THREAD

**Issue by alknemeyer** [eclipse-cyclonedds/cyclonedds-python#121]
I already mentioned this in issue #120, thinking that it was just a documentation issue, but it doesn't look like that now.

I tried increasing the timeout to 20 seconds, and the program did wait that long, but still timed out/didn't work in the end. So I'll track any debugging progress here :)

**Comment by thijsmie** [comment]
Thanks for digging in! If you would be willing to record a trace on a publisher of said type and on the python end too, I can look at the TypeInfo requests on the wire (or maybe you'll actually get a clue from the logs too). You can enable logging and packet capture using the xml config options [//CycloneDDS/Domain/Tracing/PacketCaptureFile](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaintracingpacketcapturefile) and [//CycloneDDS/Domain/Tracing/Verbosity](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaintracingverbosity)

**Comment by alknemeyer** [comment]
Sure: [recordings.zip](https://github.com/eclipse-cyclonedds/cyclonedds-python/files/9207189/recordings.zip). For that test, I recorded a single publisher and the `cyclonedds typeof` command. There were no other subscribers (I left them out to make the logs simpler, but there were subscribers for my earlier tests)

I'm reading the spec but am still not familiar with DDS internals, so I'm not sure what's going on or what to expect from the logs.

**Comment by thijsmie** [comment]
Hi @alknemeyer,

The recording did not yield any actionable results for me. Would you be able to share the IDL that causes these problems for you? You can also do so privately by sending them to thijs.miedema _at_ zettascale.tech if needed. That way I can trace what is happening in a debugger and see on which typerequest it fails and _hopefully_ also why that happens.

**Comment by alknemeyer** [comment]
I can do you one better! Steps for me to recreate the problem are as follows:

1. build CycloneDDS-Python using the instructions in the "Via Git" section of the README. When using an installed CycloneDDS, use the latest version (master branch).

2. Clone another copy of CycloneDDS, checkout the 0.9.1 tag, and build the RoundTrip example. I used the following setup:
    ```bash
    cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_LOCATION_091 -DBUILD_EXAMPLES=ON -DENABLE_TYPE_DISCOVERY=YES -DENABLE_TOPIC_DISCOVERY=YES ..
    ```

3. Make a config file as follows to enable topic discovery:

  ```xml
  <?xml version="1.0" encoding="UTF-8" ?>
  <CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
      <Domain id="any">
          <Discovery><EnableTopicDiscoveryEndpoints>true</EnableTopicDiscoveryEndpoints></Discovery>
      </Domain>
  </CycloneDDS>
  ```

4. Run the examples:  `CYCLONEDDS_URI=~/kopernikus/cyclonedds.xml bin/RoundtripPing 0 0 0` and `CYCLONEDDS_URI=~/kopernikus/cyclonedds.xml bin/RoundtripPong`

5. Run the analyser: `cyclonedds typeof RoundTrip` which produces the same output: 
![image](https://user-images.githubusercontent.com/19974131/183616257-15bb78b9-01d5-4a16-b2a2-13d24b785610.png)

You seem to be hinting that it's the IDL that's the problem, but I suspect the issue lies with using the latest version of CycloneDDS and CycloneDDS-Python together, when any deployment of CycloneDDS probably uses v0.9.1 at latest? Any thoughts? I can still send you my IDL files if you want.

**Comment by alknemeyer** [comment]
Oh, and just to confirm, if I do the steps above but run the RoundTrip example from the master branch, everything works fine. So type discovery seems to require a feature or bug fix that took place between [`0.9.1...master`](https://github.com/eclipse-cyclonedds/cyclonedds/compare/0.9.1...master) of CycloneDDS? I'm having a look now

**Comment by alknemeyer** [comment]
I used Git bisect and _may_ have found the issue. [This commit](https://github.com/eclipse-cyclonedds/cyclonedds/commit/514569142cd942addeac42dd418be1f514e4056e) is first one which fixes the issue (ie, the parent c1108239557bd4f025cd37d944c13caec09fd1c9 fails). I don't know much about the XTypes spec, but it looks like a bug got fixed in that PR?

**Comment by thijsmie** [comment]
Thanks for the excellent investigate work. Indeed, this changes the semantics of type lookups slightly which means the dynamic type resolution will not interoperate between master and 0.9. This is not really a solvable thing, we either should release 0.10 with the fix or backport the tools to 0.9.

**Comment by eboasson** [comment]
... or backport the type lookup fix and do 0.9.2?

I'm tempted to go for a 0.10 though ...

**Comment by thijsmie** [comment]
I don't think it is good to have type lookup incompatibilities between patch versions of 0.9 so I am a proponent of 0.10 😁

**Comment by eboasson** [comment]
A 0.10 it shall be!

It is about time anyway. Let's see if there's anything in the pipeline we really have to wait for, e.g. I think we really should look into the latest findings on #1345.

**Comment by alknemeyer** [comment]
Great, thank you!
