### ISSUE TITLE
Dynamic topic discovery fails when using multicast.

### ISSUE THREAD

**Issue by matte1** [eclipse-cyclonedds/cyclonedds-python#125]
I'm trying to use dynamic discovery with multicast but am getting the following error. Disabling multicast fixes this issue. 

```
  File "python_deps_cyclonedds_nightly/cyclonedds/dynamic.py", line 57, in get_types_for_typeid
    raise DDSException(ret, f"Could not fetch typeobject for {tid}")
cyclonedds.core.DDSException: [DDS_RETCODE_TIMEOUT] A timeout has occurred. Could not fetch typeobject for TypeIdentifier[Union](242, b'\x98+\xe9n&|l\xdd^\xe3o`$\xff')
```
My test setup looks like two nodes on the same network with a router between them.

**Comment by thijsmie** [comment]
Hmm, it is quite strange that the normal communication succeeds but then the typelookup fails. It might be just a question of timeouts set too low? I've already discovered elsewhere (https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/121) that I set the defaults too low so I'll up them. @dpotman are you aware of any other interactions between TypeRequest/Response and multicast?

**Comment by dpotman** [comment]
@thijsmie no, I'm not aware of that, the type lookup request and response are sent as multicast, not to a specific node. There may be multiple nodes responding to a request (in case more nodes know the requested type), but the contents from additional response messages will be discarded in case the type is resolved (optimization of this is planned). It may be helpful to enable Cyclone trace logging to see if the type lookup requests are received and what types are requested?

**Comment by matte1** [comment]
Here is my config file if its helpful!

```
<?xml version="1.0" encoding="UTF-8" ?>

<CycloneDDS>
  <Domain id="any">
    <Discovery>
      <EnableTopicDiscoveryEndpoints>true</EnableTopicDiscoveryEndpoints>
      <Peers>
        <Peer address="192.168.0.137"/>
        <Peer address="localhost"/>
      </Peers>
      <ParticipantIndex>auto</ParticipantIndex>
    </Discovery>
    <General>
      <AllowMulticast>true</AllowMulticast>
      <EnableMulticastLoopback>true</EnableMulticastLoopback>
      <MaxMessageSize>65500B</MaxMessageSize>
    </General>
  </Domain>
</CycloneDDS>

```

**Comment by matte1** [comment]
Can you point me towards an example of how to enable / use cyclone dds trace for python?

**Comment by eboasson** [comment]
Hi @matte1, it is the same for all languages, you just add:
```XML
<Tracing>
  <Verbosity>finest</Verbosity>
  <OutputFile>cdds.log.${CYCLONEDDS_PID}</OutputFile>
</Tracing>
```

the XML file.

You can vary the verbosity a bit, but this is just about the most detailed variant, and the file name defaults to `cyclonedds.log` if you don't specify one. I just added it to show you can fairly easily get the process id in there as well, that's often useful if you start multiple processes 🙂.

**Comment by matte1** [comment]
Thanks! I increased the timeout for the builtin data reader and the issue seems to have cleared up..
