### ISSUE TITLE
Again, How to connect the python helloworld with the C++ helloworld? 

### ISSUE THREAD

**Issue by wuxianshen** [eclipse-cyclonedds/cyclonedds-python#141]
This issue is from How to connect the python helloworld with the C++ helloworld? #139
Sorry to disturb again, but after change the typename, I still cannot connect C++ with python;

The C++ codes:
`
int main (int argc, char ** argv)
{
dds_entity_t participant;
dds_entity_t topic;
dds_entity_t writer;
dds_return_t rc;
HelloWorldData_Msg msg;
uint32_t status = 0;
(void)argc;
(void)argv;

//int dds_domain = 0; //DDS_DOMAIN_DEFAULT
int dds_domain = DDS_DOMAIN_DEFAULT;
participant = dds_create_participant (dds_domain, NULL, NULL);
if (participant < 0)
DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));

topic = dds_create_topic (
participant, &HelloWorldData_Msg_desc, "HelloWorldData_Msg", NULL, NULL);
if (topic < 0)
DDS_FATAL("dds_create_topic: %s\n", dds_strretcode(-topic));

writer = dds_create_writer (participant, topic, NULL, NULL);
if (writer < 0)
DDS_FATAL("dds_create_writer: %s\n", dds_strretcode(-writer));
msg.userID = 1;
msg.message = "Hello World";

printf ("=== [Publisher] Writing : ");
printf ("Message (%"PRId32", %s)\n", msg.userID, msg.message);
fflush (stdout);

rc = dds_write (writer, &msg);
if (rc != DDS_RETCODE_OK)
DDS_FATAL("dds_write: %s\n", dds_strretcode(-rc));

rc = dds_delete (participant);
if (rc != DDS_RETCODE_OK)
DDS_FATAL("dds_delete: %s\n", dds_strretcode(-rc));

return EXIT_SUCCESS;
}
`

The python code:
`
https://github.com/DataClass
class HelloWorldData(IdlStruct, typename="HelloWorldData::Msg"):
userID: int
message: str

def cdds_demo():
dp = DomainParticipant()
tp = Topic(dp, "HelloWorldData_Msg", HelloWorldData)
dr = DataReader(dp, tp)
while True:
samples = dr.read()
if len(samples) == 0:
continue
sample = samples[0]
print(f'Msg id {sample.userID}, content {sample.message}')
`

The C++ publisher and subscriber work fine;
Also, the python publisher and subscriber work fine;
But C++ publisher and python subscriber cannot connect.

Is there any other errors here?

The python-binding is installed with:
D:\Software\Anaconda3\envs\pycycdds\python.exe -m pip install git+https://github.com/eclipse-cyclonedds/cyclonedds-python

**Comment by wuxianshen** [comment]
#139 

https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/139#issuecomment-1228640480

https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/139#issuecomment-1229104646

https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/139#issuecomment-1229105331

**Comment by eboasson** [comment]
Hi @wuxianshen, I am closing this issue because it really doesn't add anything to https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/139#issuecomment-1229105331. It is not like we have been ignoring you.
