### ISSUE TITLE
Is is possible to set default value for IDL struct?

### ISSUE THREAD

**Issue by CodingTaoTao** [eclipse-cyclonedds/cyclonedds-python#143]
Version:
cyclonedds: 0.10.1
cyclonedds-python: 0.10.1

Is is possible to set default value for IDL struct?
I have a nested struct defined in python, how could I set default value for the struct, like all zeros for data?

```
@dataclass
class mm_eeg_channel_data_t(IdlStruct, typename="EEGData::mm_eeg_channel_data_t"):
    data: array[uint8, DDS_EEG_ONE_CHANNEL_BYTES]

@dataclass
class mm_eeg_sample_data_t(IdlStruct, typename="EEGData::mm_eeg_sample_data_t"):
    channels: array[mm_eeg_channel_data_t, DDS_EEG_ONE_SAMPLE_CHANNELS]

@dataclass
class mm_eeg_data_packet_t(IdlStruct, typename="EEGData::mm_eeg_sample_data_t"):
    timestamp: uint64
    packet_idx: uint32
    samples: array[mm_eeg_sample_data_t, DDS_EEG_ONE_PACKET_SAMPLES]

@dataclass
class HelloWorldData(IdlStruct, typename="EEGData::Msg"):
    userID: int32
    key("userID")
    message: str
    data: mm_eeg_channel_data_t
```

**Comment by eboasson** [comment]
Hi @CodingTaoTao I am afraid the best I can do is to just label it as a question. I am sure @thijsmie will get around to answering your question soon enough.

**Comment by thijsmie** [comment]
Hi @CodingTaoTao,

There is no support for the `@default` annotation yet, but that doesn't have to stop you in Python. The `IDLStruct`s are normal dataclasses, meaning you can use the `dataclasses.field` function to create a `default` or `default_factory`. Have a look at [the official documentation](https://docs.python.org/3/library/dataclasses.html) to see how that works.

This does unfortunately mean you have to edit autogenerated code if you use the IDL compiler. There is some limited ways around that by using subclassing but I don't think that is better.
