### ISSUE TITLE
cyclonedds-python subscribe to partition not working

### ISSUE THREAD

**Issue by smnrgrs** [eclipse-cyclonedds/cyclonedds-python#154]
I am trying to get a simple subscribe app to work, receiving data from OpenDDS 3.22. 
If I leave the partition name as default, cyclone receives data from OpenDDS.
If I set a partition name at both ends I get no data. Cyclonedds ls does not show the partition name in the QoS for cyclone so I'm wondering if cyclone python is at fault.

Here's an example of how I set my partition name:
qos = Qos(
	Policy.Reliability.BestEffort,
	Policy.Ownership.Shared,
	Policy.Durability.Volatile,
	Policy.History.KeepLast(1),
	Policy.DestinationOrder.BySourceTimestamp,
	Policy.Liveliness.Automatic(lease_duration=duration(seconds=5)),
	Policy.Partition(partitions=("a"))
)

When I have more time I'll try testing between Cyclone Python and Cyclone C++.

**Comment by thijsmie** [comment]
Hi @smnrgrs,

The partition QoS is something that applies to publishers and subscribers, not readers and writers, have you taken that into account? It's honestly something that we should give a warning about in the API.

If that doesn't solve your problem then please get back to me, then we might have a bug on our hands 🤩

**Comment by smnrgrs** [comment]
Ah, thanks for pointing that out, probably my mistake! I'll retest and let you know.

**Comment by thijsmie** [comment]
I did a quick test confirming that:

 - setting Partition QoS on Publishers/Subscribers gets writers/readers below a partition
 - setting Partition QoS on a datawriter/reader that implicitly creates their publisher/subscriber gets a partition
 - setting Partition QoS on a datawriter/reader on an existing publisher/subscriber without Partition QoS does _not_ get a partition

That last one is confusing if you don't know Partition is a Publisher/Subscriber QoS and maybe we should emit a warning....
If you have solved your problem @smnrgrs then we can close this :smile:

**Comment by smnrgrs** [comment]
Applying the partition QoS to the subscriber fixes the issue. Thanks for your help.
