### ISSUE TITLE
Is there a way to read in .idl files

### ISSUE THREAD

**Issue by jogehl** [eclipse-cyclonedds/cyclonedds-python#156]
Sorry for asking but is there a way to parse .idl files and generate python classes from this or is the only possibility to write them from scratch? I can't find such a tool but it would be very useful.

Best regards

**Comment by thijsmie** [comment]
Hi @jogehl,

If you have installed cyclonedds and cyclonedds-python from source _or_ just typed `pip install cyclonedds` you will have an executable `idlc` that you can use to turn idl files into python. Simply type `idlc -l py file.idl` in your terminal.

**Comment by jogehl** [comment]
@thijsmie thanks a lot for your answer. This helped me a lot. Is there a way to solve mulit imports in idls? I always get the error that `ifndef MODULE` is already defined  by another idl which have imported it. For example I use a math idl and it is used in mulitple idls A,B.  Later on I import A and B in C.

**Comment by thijsmie** [comment]
Hi @jogehl,

I have some trouble understanding your exact issue. Can you give me an example with IDL files that causes the issue and the steps to reproduce?

**Comment by jogehl** [comment]
I think I have solved the problem. Thanks a lot
