### ISSUE TITLE
Sort imports generated by idlc and format

### ISSUE THREAD

**Issue by AkhilTThomas** [eclipse-cyclonedds/cyclonedds-python#160]
I have a python formatter running in vscode which sorts imports on files when saved. This is making changes to the generated python code from idl. There are quite a lot of files generated as my idl is pretty huge. (Messes up the git history also)
It would be nice if the imports where already declared in sorted order. I can also create a PR for this. What do you say? :)

From
`  
from enum import auto`  
`from typing import TYPE_CHECKING, Optional`
`from dataclasses import dataclass`
`import cyclonedds.idl as idl`
`import cyclonedds.idl.annotations as annotate`
`import cyclonedds.idl.types as types`

To

`from dataclasses import dataclass`
`from enum import auto`
`from typing import TYPE_CHECKING, Optional`  
`import cyclonedds.idl as idl`
`import cyclonedds.idl.annotations as annotate`
`import cyclonedds.idl.types as types`

**Comment by AkhilTThomas** [comment]
More formatting options
From
`__all__ = ["IsActive", "IsEnabled", "IsError", "SpeedSet", ]`
To
`__all__ = [`
`    "IsActive",`
`    "IsEnabled",`
`    "IsError",`
`    "SpeedSet",`
`]`

**Comment by thijsmie** [comment]
Hi @AkhilTThomas,

I don't mind merging this change so if you're willing to go through making a PR I'll do so. I do find it questionable to allow your IDE to dictate your workflow and make auto-edits to generated files, but that is none of my business of course :smile:.

**Comment by AkhilTThomas** [comment]
> Hi @AkhilTThomas,
> 
> I don't mind merging this change so if you're willing to go through making a PR I'll do so. I do find it questionable to allow your IDE to dictate your workflow and make auto-edits to generated files, but that is none of my business of course 😄.
Thank you 😃 
It does make sense in some way that all code follow certain rules or style. 🙈

**Comment by AkhilTThomas** [comment]
@thijsmie Is there a documentation on compiling just the idlc py?

**Comment by thijsmie** [comment]
You cannot just compile the idlc py, you need the core idlc libraries. If you have the core idlc and libraries the python idl library is compiled as any Python extension would be so you can also do that just with gcc. I'm  just typing this from the top of my head so you might need to adjust it if I make a typo 😇 :

````bash
cd idlpy
gcc -o obj/context.o -c -context -Isrc -I/path/to/cyclonedds/include src/context.c
gcc -o obj/generator.o -c -Iinclude -Isrc -I/path/to/cyclonedds/include  src/generator.c
gcc -o obj/naming.o -c -Iinclude -Isrc -I/path/to/cyclonedds/include src/naming.c
gcc -o obj/ssos.o -c -Iinclude -Isrc -I/path/to/cyclonedds/include src/ssos.c
gcc -o obj/types.o -c -Iinclude -Isrc -I/path/to/cyclonedds/include src/types.c
gcc -o obj/util.o -c -Iinclude -Isrc -I/path/to/cyclonedds/include src/util.c
gcc -o lib/idlpy.so -L/path/to/cyclonedds/lib -lcycloneddsidl obj/*
``
