### ISSUE TITLE
idlc python output name conflicts with cyclonedds.idl

### ISSUE THREAD

**Issue by JacobJBeck** [eclipse-cyclonedds/cyclonedds-python#161]
Using `idlc -l py` creates a module named 'idl'. This is problematic because within that module, generated scripts have these lines:
```
import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import idl
```

This causes `AttributeError: partially initialized module 'idl' has no attribute 'IdlEnum' (most likely due to a circular import)` due to the overlap in names. Renaming the module and replacing the line `import idl` with the new name resolves the issue.

**Comment by thijsmie** [comment]
Yeah that is indeed something I hadn't considered. @javiersorianoruiz how is your keyword filter coming along? We should also add `idl`, `annotate` and `types` as reserved identifiers....

**Comment by thijsmie** [comment]
This should be fixed on the master branch.
