### ISSUE TITLE
Is it possible to add a function case about dynsub

### ISSUE THREAD

**Issue by lflxp** [eclipse-cyclonedds/cyclonedds-python#175]
I just contacted Cyclonedds. Is it possible to add a function case of dynsub implemented in python

**Comment by thijsmie** [comment]
Hi @lflxp,

There is the dynamic type discovery API in python as documented [here](https://cyclonedds.io/docs/cyclonedds-python/latest/cyclonedds.dynamic.html). It is used by the `cyclonedds subscribe [topic]` command line tools to do dynsub. You can find the source for this tool [here](https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/master/cyclonedds/tools/cli/sub.py).

**Comment by lflxp** [comment]
> Hi @lflxp,
> 
> There is the dynamic type discovery API in python as documented [here](https://cyclonedds.io/docs/cyclonedds-python/latest/cyclonedds.dynamic.html). It is used by the `cyclonedds subscribe [topic]` command line tools to do dynsub. You can find the source for this tool [here](https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/master/cyclonedds/tools/cli/sub.py).

I have spent two days trying to solve this problem. Now I understand where to start. Thank you
