### ISSUE TITLE
[Question] How to set a reasonable name for participant in python?

### ISSUE THREAD

**Issue by morkovka1337** [eclipse-cyclonedds/cyclonedds-python#205]
Hello,

So far I can set the domain ID when I create a participant using this code:
`dp = DomainParticipant(2)`

But such domain has a random hash name in `cyclonedds ps`:
<img width="696" alt="image" src="https://github.com/eclipse-cyclonedds/cyclonedds-python/assets/32310433/842bc2e4-f1d7-4076-bb60-5ca4a4113798">
Is there a way to set a reasonable (string) name for participant?

**Comment by eboasson** [comment]
Like this:
```
DomainParticipant(0, Qos(Policy.EntityName("dihydrogenmonoxide")))
```
you mean?

<img width="939" alt="image" src="https://github.com/eclipse-cyclonedds/cyclonedds-python/assets/16984005/a97583d2-5b3b-432b-8d8f-3ddc496b4126">

**Comment by morkovka1337** [comment]
Exactly! Thanks
