### ISSUE TITLE
Windows platform environment not work

### ISSUE THREAD

**Issue by djh12345678** [eclipse-cyclonedds/cyclonedds-python#206]
"How to configure environment variables on Windows platform? I used the code: 
`from os import environ
environ['CYCLONEDDS_URI'] =r'D:\config\cyclonedds_pub.xml'

, but it didn't work."

**Comment by eboasson** [comment]
I don't know, sorry. If I did know the answer, I'd give it, of course. It is really a Python/Windows question and not a Cyclone DDS one, so I would advise checking the forums there.

Good luck!
