### ISSUE TITLE
PyPi - cyclonedds version not up-to-date 

### ISSUE THREAD

**Issue by trittsv** [eclipse-cyclonedds/cyclonedds-python#234]
The python cyclonedds version is not up-to-date on pypi.

https://pypi.org/project/cyclonedds/ still has 0.10.2, but the current version is 0.10.4.

**Comment by windelbouwman** [comment]
Agreed, it would also be handy to have binary builds available using the python stable API.

https://docs.python.org/3/c-api/stable.html#stable-abi

**Comment by amolkambar** [comment]
you can build whichever version you want from the git, and can build a wheel which you can share with others.
Please note that, the builds will be platform and python version specific. Even different version of python will not be able to install the package with a given wheel.

**Comment by trittsv** [comment]
pypi packages are updated now
