### ISSUE TITLE
Setting Unions with no value

### ISSUE THREAD

**Issue by FirebarSim** [eclipse-cyclonedds/cyclonedds-python#245]
This is more of a cry for help than an issue. I am attempting to work with the OARIS IDL from the OMG. This spec uses a number of Union types to indicate if data is present, but for the life of me I cannot figure out how to use the union types when data is not present!

For example
cartesian_position_z_coordinate_type(discriminator=cartesian_coordinate_type, value=7)
Seems to parse ok, but
cartesian_position_z_coordinate_type()
cartesian_position_z_coordinate_type(discriminator=False)
cartesian_position_z_coordinate_type(discriminator=None)
Etc do not. 

I suspect I have the wrong end of the stick on unions and would appreciate a pointer!

**Comment by eboasson** [comment]
Hi @FirebarSim, I had to give it some thought, but I found it. The trick is `discriminator=False, value=None`:

```Python
from time import sleep
from cyclonedds.domain import DomainParticipant
from cyclonedds.pub import DataWriter
from cyclonedds.topic import Topic

# u.idl:
'''
@appendable
union U switch (boolean) {
  case TRUE: string v;
};

@appendable
struct S {
  U v;
};
'''

from u import U, S

dp = DomainParticipant(0)
tp = Topic(dp, "S", S)
dw = DataWriter(dp, tp)

b = 0
while True:
    if b == 0:
        dw.write(S(v=U(discriminator=False, value=None)))
        b = 1
    elif b == 1:
        dw.write(S(v=U(discriminator=True, value="strand")))
        b = 2
    else:
        dw.write(S(v=U(v="bolderkar")))
        b = 0
    sleep(1)
```
running `dynsub S` in parallel then prints:
```
dds_find_topic: Timeout ... continuing on the assumptions that topic discovery is disabled
  1 STRUCTURE typename=S typeflags={IS_APPENDABLE}
  2   name=v memberid=0x0 memberflags={TRY_CONSTRUCT1}
  3     COMPLETE id=b32c1699e3de24481eead5a00dab
  4       UNION typename=U typeflags={IS_APPENDABLE}
  5         discriminator=memberflags={TRY_CONSTRUCT1,IS_MUST_UNDERSTAND} BOOLEAN
  6         case 1:
  7           name=v memberid=0x0 memberflags={TRY_CONSTRUCT1}
  8             STRING8_SMALL bound=0
{"v":{"_d":false}}
{"v":{"_d":true,"v":"strand"}}
{"v":{"_d":true,"v":"bolderkar"}}
{"v":{"_d":false}}
```

**Comment by FirebarSim** [comment]
Thankyou! I think you have pointed me at something. Could you try the exact same code except with this IDL as a sanity check?

# u.idl:
'''
@appendable
union U switch (boolean) {
  case TRUE: string value;
};

@appendable
struct S {
  U v;
};

I think the issue I am hitting is that OARIS has a lot of Unions where “value” is used as the field name. Then cyclonedds-python is breaking and not serializing correctly because value refers to something specific?

**Comment by FirebarSim** [comment]
Glad to know I’ve not gone insane, for my purposes I just changed the generated module files manually, value: became val:, which is now happily talking away to an opensplice instance on another machine. I think your suggestion of a change in the IDL processor sounds appropriate.
