### ISSUE TITLE
Building cyclondedds from git for python

### ISSUE THREAD

**Issue by amolkambar** [eclipse-cyclonedds/cyclonedds-python#247]
Hello,
While installing cyclonedds though pypi gives error.

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      Could not locate cyclonedds. Try to set CYCLONEDDS_HOME or CMAKE_PREFIX_PATH
      [end of output]

Machine:
        $ cat /etc/os-release
        PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
        NAME="Debian GNU/Linux"
        VERSION_ID="12"

Built with git, but once python is launched,
import cyclonedds fails, unless I specify the environment variable path which is CYCLONEDDS_HOME.

Is there a way to make it work as a normal python package, without needing to look for the *.so files in the cyclonedds/install directory?
that is to install and use cyclonedds without the git repository being a dependency? 

I tried with pypi method of installation, but that fails with the following error:
$ pip3 install cyclonedds --no-binary cyclonedds
              .
              clayer/pysertype.c:23:10: fatal error: dds/ddsi/q_radmin.h: No such file or directory
                 23 | #include "dds/ddsi/q_radmin.h"
                    |          ^~~~~~~~~~~~~~~~~~~~~
              compilation terminated.
              error: command '/usr/bin/gcc' failed with exit code 1
              [end of output]
  
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cyclonedds
      Failed to build cyclonedds

Any help is much appreciated, thanks in advance.!

**Comment by LY1806620741** [comment]
我觉得你需要安装wheel二进制包，他包含了C语言动态库。I think you need to install the wheel binary package, which contains the C language dynamic library.

https://pypi.org/project/cyclonedds/0.10.2/#files

**Comment by amolkambar** [comment]
Thanks for your response, this works.
However, anyone struggling with installation of with wheel, check for cp310 or cpXXX which is the version of cpython supported, make sure you have the same python version while installing through pip (higher version fails as well).
