### ISSUE TITLE
Subscribe to a topic on a dedicated partition

### ISSUE THREAD

**Issue by aratar-orome** [eclipse-cyclonedds/cyclonedds-python#268]
Hi,

Frist of all, thank you for that great monitoring feature for CycloneDDS.

I am on the master branch of CycloneDDS and use the nightly build of cyclonedds-python.

I used the subscription function already successful. My problem is that the topic on which I have subscribed is published with different QoS/partition settings and I want only subscribe the topic from a specific partition. 

I used the tool so:
cyclonedds subscribe --qos scan TOPIC 

According to the docu I should get a prompt for input, but I did not get any.

**Comment by aratar-orome** [comment]
I know it is not a real issue, but I would really appreciate some help so I get the must out of the tool. Thanks

**Comment by eboasson** [comment]
Thank you for persevering despite a lack of responses and for sharing the conclusion!
