### ISSUE TITLE
Getting error when trying to install cyclonedds in python using pip. 

### ISSUE THREAD

**Issue by avelin0** [eclipse-cyclonedds/cyclonedds-python#272]
(.venv) PS C:\Users\av\PycharmProjects\proj-cyclonedds> pip install cyclonedds
Collecting cyclonedds
  Using cached cyclonedds-0.10.5.tar.gz (156 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      Could not locate cyclonedds. Try to set CYCLONEDDS_HOME or CMAKE_PREFIX_PATH
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by DARKMOONlite** [comment]
set the `CYCLONEDDS_HOME` variable to whereever you installed [cyclone DDS](https://github.com/eclipse-cyclonedds/cyclonedds)

**Comment by avelin0** [comment]
Thankx you
