### ISSUE TITLE
Listener notification thread hangs while removing DataWriter

### ISSUE THREAD

**Issue by jarekdr** [eclipse-cyclonedds/cyclonedds-python#31]
Hi,
while the python try to remove `DataWriter` object within the listener notification thread, the thread hangs. 
Below is a simple program to reproduce it. First `DataWriter` linked with `response_topic` is created, and then `DataReader` linked with `alive_topic` within the same process. So the reader and writer are linked with different topics, and reader has set listener for `on_liveliness_changed`. Next the simple publisher program (running in the separate process) create a `DataWriter` linked with `alive_topic`. When the publisher process stops, `on_liveliness_changed` event in the first process arise, and when there are no more matched writers, `DataWriter` is removed from `list` in the listener method. Since reference to `DataWriter` was only on the `list`, python try to remove that object. But when it calls `__del__` in `core.py`, it get stucked at `def _delete(self, entity: dds_c_t.entity)`

Main program
```
list = []
class CustomListener(Listener):

    def on_liveliness_changed(self, reader, status) -> None:
        if status.alive_count == 0:
            list.pop(0)
            return


dp = DomainParticipant(0)
publisher = Publisher(dp)

response_topic = Topic(dp, 'response_topic', Message, qos=QOS)
list.append(DataWriter(publisher, response_topic))

alive_topic = Topic(dp, 'alive_topic', Message, qos=QOS)
reader = DataReader(dp, alive_topic, listener=CustomListener())

sleep(120)
```

Simple publisher

```
    dp = DomainParticipant(0)
    publisher = Publisher(dp)
    topic = Topic(dp, 'alive_topic', Message, qos=QOS)
    writer = DataWriter(publisher, topic)

    for i in range(1,5):
        print(".")
        writer.write(Message('.'))
        sleep(1)
```

Moreover in the provided example the `on_livenliness_changed` callback was used, but the same situation happens when removing is in the `on_data_available`, regardless publisher already sent or not samples. Reading the issue https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/7,  it was mentioned that call writers is not prohibited in callback until it doesn't concert the same entity. Here I have different topics, so the question is what else could be wrong here?

Thanks in advance

**Comment by thijsmie** [comment]
Hi @jarekdr, thanks for your report.

I've verified your problem with a reproducer both in Python and in C, I will have to do some more investigation as to how the deadlock (or mutual conditional variable wait I think) state comes to be.
Personally I think it is best to avoid doing DDS related things inside a listener callback. Blocking your main execution thread with a sleep and then doing things in the `Listener` tells me you could also work with a `WaitSet` or build a simple polling mode and look at the entity status bits.
If you want to keep the current style you could for now spin up a `threading.Thread` and set a `threading.Event` from the listener and delete the `DataWriter` from the thread, or set a boolean on the `Listener` and poll for it in a main loop.

I hope this helps for now, to be continued.

**Comment by thijsmie** [comment]
I am sorry this has remained open so long, but this is purely a result of the way locking and listener dispatch works. To keep things *lean and mean* listeners are dispatched synchronously from the event occurring, which keeps latencies as low as possible. However, this means that some functionality is not available inside listener events since resources related to the listener might be locked. Deleting entities inside a listener is one such thing which you should not attempt.

**Comment by jarekdr** [comment]
Ok. It would be worth to mention this in the Listener class file.
