### ISSUE TITLE
GuideExample test

### ISSUE THREAD

**Issue by Eyuel-Military-Project** [eclipse-cyclonedds/cyclonedds-python#38]
Do you have a guide/commands to test simple publisher/subscriber communication example to test/start with the cyclonedds-python? I couldn't find any specific guidelines on that

**Comment by thijsmie** [comment]
Hi @Eyuel-Military-Project,

The [Vehicle example](https://github.com/eclipse-cyclonedds/cyclonedds-python/tree/master/examples/vehicle) should help you get started. You can also build the python docs with Sphinx (they will be published on cyclonedds.io hopefully soon) for some more information.

For a more advanced example you can also look at the included `ddsls` and `pubsub` tool source codes under cyclonedds/tools.

Let me know if you need help with anything in particular.

**Comment by thijsmie** [comment]
I think this problem is solved, so I am closing this issue. @Eyuel-Military-Project if you have any further comments let me know and I'll gladly reopen this issue.
