### ISSUE TITLE
on_data_available functor used instead of on_sample_rejected

### ISSUE THREAD

**Issue by pbleyer** [eclipse-cyclonedds/cyclonedds-python#5]
https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/334132cdcad1330b766aa408e6290583d93f51bc/src/cyclonedds/cyclonedds/core.py#L747

Should be `self._set_functors["on_sample_rejected"] = self.on_sample_rejected`

**Comment by thijsmie** [comment]
Thank you @pbleyer for spotting this mistake, and also thank you for being the first issue reporter to CycloneDDS-Python!

**Comment by thijsmie** [comment]
@eboasson Text parsing is always hard, "Fix issue #5" was not good enough, that word 'issue' ruins the linking between PR and Issue. Anyway, this is fixed and should be closed.
