### ISSUE TITLE
Where to set network interface used by Listener, etc.?

### ISSUE THREAD

**Issue by pscheie** [eclipse-cyclonedds/cyclonedds-python#59]
This isn't an issue, it's a question: Where do I specify the ethernet device that Listener, Subscriber, Publisher, and DataWriter should use?  I have a host with multiple NICs and I need to specify which NIC they bind to (although not needing to know that sort of stuff is kinda the point of DDS, isn't it. ;-))

**Comment by thijsmie** [comment]
Hi pscheie! 

You can specify a config file using the environment variable CYCLONEDDS_URI and pointing to a config file. You can see how to write them [here](https://github.com/eclipse-cyclonedds/cyclonedds#configuration) and [here](https://cyclonedds.io/docs/cyclonedds/latest/config.html). Hope that helps!

**Comment by pscheie** [comment]
Hi @thijsmie,
Yes, those links are very helpful.  Thanks!  (Serves me right for not having scrolled down the page on the cyclonedds-python homepage).

**Comment by pscheie** [comment]
Can CYCLONEDDS_URI be set from within my python script?  Running 'export CYCLONEDDS_URI=file://home/pscheie/cyclonedds/cyclonedds.xml' and then calling my python cyclonedds program works.  But I'd rather setup the environment variable within the python program so I don't have to remember to export CYCLONEDDS_URI.  I tried

from os import environ
environ['CYCLONEDDS_URI'] = '/home/pscheie/cyclonedds/cyclonedds.xml'

but it doesn't work, i.e., the xml file doesn't get read when the program is run.  Can CYCLONEDDS_URI be set within the python program itself?

**Comment by eboasson** [comment]
HI @pscheie I don't actually know the answer to your question (I would assume it could be done, but I don't actually know). What I wanted to point out is that you can create a domain entity explicitly using the `Domain` class, and that allows you to pass in the path to the configuration file (or even the XML configuration itself).

After you create the domain, you can then create participants just like normal.

**Comment by thijsmie** [comment]
Just to chime in again, that os.environ trick should also work, you have to watch the import order though: the variable should be set before you import cyclonedds.

**Comment by pscheie** [comment]
Hey @eboasson & @thijsmie ,
You guys are great; thanks for the quick responses.  @thijsmie, you are correct, it was the import order I had wrong.  I moved the os.environ call ahead of importing of the cyclonedds modules and then it worked perfectly, that is, the settings in the xml file were used.  @eboasson, pulling in the xml file when instantiating the Domain class seems even more elegant.  I think that might be a better approach than os.environ (have to play around with it a bit to see).

Thanks for your help.

**Comment by pscheie** [comment]
Hey @eboasson & @thijsmie ,
You guys are great; thanks for the quick responses.  @thijsmie, you are correct, it was the import order I had wrong.  I moved the os.environ call ahead of importing of the cyclonedds modules and then it worked perfectly, that is, the settings in the xml file were used.  @eboasson, pulling in the xml file when instantiating the Domain class seems even more elegant.  I think that might be a better approach than os.environ (have to play around with it a bit to see).

Thanks for your help.
