### ISSUE TITLE
release roadmap

### ISSUE THREAD

**Issue by ghorn** [eclipse-cyclonedds/cyclonedds-python#63]
What needs to be done before this project is released? I would like to use it in a project where installation from source is impossible, but installation from PyPi is straightforward. It would also be helpful if you had any idea of the possible effort/timeline. Thanks!

**Comment by eboasson** [comment]
The plan is to get `cyclonedds`, `cyclonedds-cxx` and `cyclonedds-python` released or at the very least "release-candidated" (we do have to sync up with Eclipse Iceoryx and ROS 2) before the astronomical spring of 2022, that is, before 20 March 15:33 UTC.

For that, there is no real work remaining on the python binding and it is really the last bits and pieces on C++ and C that we're doing now.

**Comment by ghorn** [comment]
Thanks!

**Comment by ghorn** [comment]
That sounds like a pretty hard deadline!

**Comment by ghorn** [comment]
Reopening because it's been a few weeks. Can I please get an update on the expected release date? Thanks!

**Comment by thijsmie** [comment]
Hi there @ghorn!

We are very close to the 0.9.0 release. In fact, we've tagged a beta already, but had some issues with CI that prevented the wheels from being pushed to PyPi. Thus the answer is: any day now!

**Comment by thijsmie** [comment]
Hi @ghorn, I am happy to inform you that we have released and that typing `pip install cyclonedds` should get you up and running in seconds now!

**Comment by ghorn** [comment]
Thank you!
