### ISSUE TITLE
serializing from C++ to python without IDL

### ISSUE THREAD

**Issue by ghorn** [eclipse-cyclonedds/cyclonedds-python#79]
I'm trying to serialize messages to a log file from C++ and read them back from Python. So far I've accomplished this using the idlc Python generator to create `IdlStruct`s which I can call `.deserialize()` on. The problem is that I expect the IDLs to change frequently, and I need to be able to read old logs, so I need to be able to parse these logs without having the IDLs available.

I've found that if I compile cyclonedds with type and topic discovery support, the idlc also generates serialized type information. My question is, is it possible to save this and load it in python, giving me an `IdlStruct` without having the original IDL available?

**Comment by thijsmie** [comment]
Hi @ghorn,

So the answer is "Yes, but..." I'll try to go over my musings in a somewhat coherent manner.

Firstly, do you need to go this route knowing `@appendable` and `@mutable` are available? With these XTypes concepts you can evolve your datamodel while maintaining backwards compatibility, thus dropping the need to retain type information.

Secondly, if you are able to store type information with the logs (the TypeInformation and TypeMapping) captured from the internal serialized type information, would it not be just as easy to 'compress' the IDL by dropping all the whitespace and save that instead? Writing a little `subprocess` wrapper around `idlc` in python is easy enough and this would make you able to parse the IDL at runtime.

Thirdly, yes, you can reinterpret the type information and reconstruct the type. However, you will need some knowledge on how the Python library works with types internally, and we promise no backwards compatibility on this internal format. You can look into `cyclonedds.dynamic` and `cyclonedds.idl._xt_builder` on how it is implemented.

**Comment by ghorn** [comment]
Thank you for the answer. I don't know about appendable and mutable, can you point me to a reference?

I could definitely compress the IDL, that sounds straightforward. I'll play around with that. I ran into some differences between the C++ serialization and the python, but it wasn't definitive, but I think that's a good approach in general. Thank you.

**Comment by thijsmie** [comment]
Right, actually, we really should do a nice explanation of what XTypes allows you to do without pointing to [the official specification](https://www.omg.org/spec/DDS-XTypes/) which is somewhat torturous to read. I'll put that on my TODO list, a very quick introduction here:

XTypes introduces a bunch of new things, but we'll focus on three new *annotations*: `@final`, `@appendable` and `@mutable`. These can be applied to a struct like so:
```idl
@final
struct A {
   long f1;
};
@appendable
struct B {
   long f1;
};
@mutable
struct C {
   long f1;
};
```
Final means, roughly, that the structure is not allowed to change. This is the behaviour you are used to from IDL. However, `@appendable` means that multiple variations of the same type are allowed to exist in the same system, as it can be updated by *appending* fields at the end. Missing fields will be default-initialised, while extra data is discarded. `@mutable` is very much the same but fields may be shuffled, dropped or added. There are two main caveats: there is a higher on-the-wire overhead to retain the information of what fields are present in binary format and you cannot change the amount, type and order of `@key` fields.

**Comment by ghorn** [comment]
The serialized IDL route is actually not straightforward for me, because I will have to chase down includes at the build system level. It is possible but not trivial as I originally had though. I'd like to take one last look at the option of deserializing the type information.

If you were me and you were going to write the function
```python
def deserialize_idl_struct(type_info_blob: bytes, type_map_blob: bytes) -> IdlStruct:
    ...
```
how would you approach it? I don't conceptually understand what would be non-portable or difficult about it, because the functionality seems to exist in the library already. `dynamic.py` seems to be close, but it is gathering the type map from the network instead. Does `TypeInformation` and `TypeMapping` contain the complete description of the type? I found `cyclonedds.idl._typesupport.DDS.XTypes._ddsi_xt_typemap.TypeMapping` but `TypeMapping.deserialize(type_map_blob)` fails for me. I'm really just failing around in the dark at this point. Thanks again for the help.

**Comment by thijsmie** [comment]
Hi @ghorn,

Indeed the TypeMapping and TypeInformation together contain everything you need. Due to the fact the blobs you have are probably stored without CDR header (that is the default in the C sources) you'll need to add `has_header=False, use_version_2=True` to the `deserialize()` call. After that you can use the `XTInterpreter.xt_to_class` with the Complete TypeID (look up in TypeInformation) and a dictionary of TypeID->TypeObject (reform from TypeMapping).

If you get stuck again send me the code you have so far and I'll be happy to PR or edit to make it work. The mixture of the different ways of representing types makes things harder than it should be but that is just what we have to live with.

**Comment by ghorn** [comment]
Thanks so much for the help, I think I'm almost there. I'm stuck on

> you can use the `XTInterpreter.xt_to_class` with the Complete TypeID (look up in TypeInformation) and a dictionary of TypeID->TypeObject (reform from TypeMapping).

I don't understand how to look up `Complete TypeID` in `TypeInformation`. Here's what I've got

```python
from cyclonedds.idl import IdlStruct
from cyclonedds.idl._typesupport.DDS.XTypes._ddsi_xt_typemap import TypeMapping
from cyclonedds.idl._xt_builder import XTInterpreter
from cyclonedds.idl._typesupport.DDS.XTypes._ddsi_xt_type_object import TypeIdentifier

def load_idl_struct(type_info_blob: bytes, type_map_blob: bytes) -> IdlStruct:
    type_id = TypeIdentifier.deserialize(type_info_blob, has_header=False, use_version_2=True)
    type_map = TypeMapping.deserialize(type_map_blob, has_header=False, use_version_2=True)
    print(type_id) 
    print(type_map)
    return XTInterpreter.xt_to_class(ident=type_id, tmap=type_map)
```
The two `deserialize` calls work, and there's an error in `xt_to_class`. I assume the error is because I'm not forming `type_id` by looking it up in TypeInformation.

I don't think it's relevant, but the error is 
```
    XTInterpreter.xt_to_class(ident=type_id, tmap=type_map)
  File "cyclonedds/idl/_xt_builder.py", line 1433, in xt_to_class
    main_type = cls._from_typeid(ident, state)
  File "cyclonedds/idl/_xt_builder.py", line 1473, in _from_typeid
    return cls._from_typeobject(ident, state)
  File "cyclonedds/idl/_xt_builder.py", line 1488, in _from_typeobject
    obj = state.database[ident]
TypeError: 'TypeMapping' object is not subscriptable
```

**Comment by ghorn** [comment]
OK so I think I was way off. Do I need something more like `XTBuilder.process_type` ?

**Comment by ghorn** [comment]
I'm sorry, but I don't know how to proceed. If you do have bandwidth for this, the function I need would be this:
```
from cyclonedds.idl import IdlStruct
from cyclonedds.idl._typesupport.DDS.XTypes._ddsi_xt_typemap import TypeMapping
from cyclonedds.idl._typesupport.DDS.XTypes._ddsi_xt_type_object import TypeIdentifier

def load_idl_struct(type_info_blob: bytes, type_map_blob: bytes) -> IdlStruct:
    type_id = TypeIdentifier.deserialize(type_info_blob, has_header=False, use_version_2=True)
    type_map = TypeMapping.deserialize(type_map_blob, has_header=False, use_version_2=True)
    ...
```

**Comment by thijsmie** [comment]
Hi @ghorn,

Here is the code you need! Under no warranty: The XTInterpreter is non-public API surface so it might change somewhere down the line.

```python
from cyclonedds.idl import IdlStruct
from cyclonedds.idl._typesupport.DDS.XTypes import TypeMapping, TypeInformation
from cyclonedds.idl._xt_builder import XTInterpreter


def load_idl_struct(type_info_blob: bytes, type_map_blob: bytes) -> IdlStruct:
    type_info = TypeInformation.deserialize(type_info_blob, has_header=False, use_version_2=True)
    type_map = TypeMapping.deserialize(type_map_blob, has_header=False, use_version_2=True)

    type_id = type_info.complete.typeid_with_size.type_id
    type_mapping_for_xt = {
        pair.type_identifier: pair.type_object
        for pair in type_map.identifier_object_pair_complete
    }

    # [0] is the top level type, [1] is a dictionary of all dependend types
    return XTInterpreter.xt_to_class(type_id, type_mapping_for_xt)[0]


# -- Test --

class A(IdlStruct):
    fa: int
    fb: str


# Serialize
type_blob = A.__idl__.get_type_info().serialize()
map_blob = A.__idl__.get_type_mapping().serialize()

# Type blobs as stored by idlc in C structs do not have a CDR header,
# But the standard python .serialize() method always adds it
# so to match the C environment we strip the CDR header (4 bytes)

type_blob = type_blob[4:]
map_blob = map_blob[4:]

print(load_idl_struct(type_blob, map_blob))
```

**Comment by thijsmie** [comment]
Hi @ghorn,

Did the code I posted work for you?

**Comment by ghorn** [comment]
yes! thank you!

**Comment by thijsmie** [comment]
Good that it worked 😄
