### ISSUE TITLE
Creating topics from dynamically discovered types fails with a typedef array

### ISSUE THREAD

**Issue by matte1** [eclipse-cyclonedds/cyclonedds-python#85]
I'm getting the following error when I attempt to instantiate a topic using a dds type that was dynamically discovered. I believe that the only change I made recently was to use typedefs in the idl for arrays.

```
topic = Topic(self._domain_participant, topic_name, topic_type)
  File "cyclonedds/topic.py", line 54, in __init__
    data_type.__idl__.populate()
  File "cyclonedds/idl/_main.py", line 106, in populate
    self.v0_machine, self.v2_machine, self.keyless, self.version_support = Builder.build_machines(self.datatype)
  File "cyclonedds/idl/_builder.py", line 311, in build_machines
    v0_machine, v2_machine, keyless = cls._machine_struct(_type)
  File "cyclonedds/idl/_builder.py", line 200, in _machine_struct
    v0_members = {
  File "python_deps_cyclonedds/cyclonedds/idl/_builder.py", line 201, in <dictcomp>
    name: cls._machine_for_type(field_type, False, False)
  File "cyclonedds/idl/_builder.py", line 178, in _machine_for_type
    raise TypeError(f"{_type} is not valid in IDL classes because it cannot be encoded.")
TypeError: typing.Any is not valid in IDL classes because it cannot be encoded.
```

The IDL looks something like the following

```
typedef double foo__double__3[3];

struct Foo {
  foo__double__3 foo_array;
};

```

Any help would be wonderful!

**Comment by matte1** [comment]
Confirmed that it works as expected for non-dynamic topics i.e. dds types that I import.

**Comment by thijsmie** [comment]
Hi @matte1,
Thanks for reporting this issue! I think I can see where the issue lies (resolve of deferred type definition is only applied for structs and unions and not for typedefs). I'll put this on my TODO list, I don't think it will be resolved in time for the 0.9.1 release we are planning this week.

**Comment by thijsmie** [comment]
Hi again @matte1,

I think I've already fixed this, could you check if https://github.com/eclipse-cyclonedds/cyclonedds-python/pull/81 fixes your issue too? For me the array type you included resolves correctly if that bugfix is applied.

**Comment by thijsmie** [comment]
Okay, I'll wait to see if the current set of fixes indeed fix your issue or if something else is still needed. The 0.9.1 release should come this week as also mentioned to ghorn.

**Comment by matte1** [comment]
Sounds good! Thanks!

**Comment by matte1** [comment]
Hi @thijsmie! Sorry I was out of town for a while. I'm getting a new error now.

`  File "......../python3_10_x86_64-unknown-linux-gnu/lib/python3.10/typing.py", line 175, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got <cyclonedds.idl._xt_builder.XTParseState.Deferred object at 0x7fc51a626e60>.
`
from the following:

` topic_type, _ = get_types_for_typeid(domain_participant, sample.type_id, duration(milliseconds=100))
`

**Comment by thijsmie** [comment]
Hmm interesting. Is this multiple processes? Could you send me the exact IDL that causes the issue? If you don't want to post it publicly you can send it to thijs.miedema  .at.  zettascale.tech

**Comment by matte1** [comment]
Multiple processes!

**Comment by matte1** [comment]
I actually just got a new error trying to create a minimal example. The setup is a C++ application publishing the following DDS message to a python application doing dynamic discovery. It seems that using a typedef multiple times causes an issue.

`#pragma once

// (no IDL files to include)

module message {
module rule {
module test2 {
module foo {
module foo__dds {

typedef float std_array__float__4[4];

struct FooTelem {
  std_array__float__4 foo;
  std_array__float__4 bar;
};
};  // module foo__dds
};  // module foo
};  // module test2
};  // module rule
};  // module message
`

error:
`l/_builder.py", line 178, in _machine_for_type
    raise TypeError(f"{_type} is not valid in IDL classes because it cannot be encoded.")
TypeError: typing.Any is not valid in IDL classes because it cannot be encoded.
`

**Comment by thijsmie** [comment]
The "using a typedef multiple times" was the critical part of this issue indeed, and that is why I didn't spot anything wrong initially. The PR I just submitted fixes the issue you are facing (and a few others, mostly edge cases in recursive types with typedefs, I believe no one is using that yet).

**Comment by matte1** [comment]
Thanks a ton!!!

**Comment by ghorn** [comment]
Any interest in making a `0.9.1.1` release for this fix?

**Comment by thijsmie** [comment]
We will stick to our current versioning scheme and pull this into a `0.9.2` release.
