### ISSUE TITLE
Publish on one network interface, subscribe on another

### ISSUE THREAD

**Issue by pscheie** [eclipse-cyclonedds/cyclonedds-python#90]
I'm building a python program that needs to subscribe to topic A on one network interface (eth0) and then use the info from that to publish to topic B on another interface (eth1).  I've previously been using an XML config file on this system to restrict the publishing to eth1; perhaps I can expand that to indicate topic A should be subscribed to on eth0 while topic B should be published to on eth1?  If so, what would that look like?

BTW, I've been away from cyclonedds for a couple of months, and wow!  You guys have done a ton of work.  I like how the example code given in the README.md for cyclonedds now uses Python.  I'm excited to try the "define the data type class within the main script' approach--perhaps this was always available and I just didn't know it but I'm glad to have learned of it.  Anyway, thanks to the whole cyclonedds team for all your efforts.

**Comment by thijsmie** [comment]
Hi @pscheie!

So there are a few ways to achieve this. Firstly, you could just not worry about it at all: if no subscribers exists for topic B in network connected by eth0, then that data will not be sent over eth0 and vice versa. Secondly, you could use the `Partition` QoS if there are also subscribers for topic B in the other subnet you don't want to send your data to. Thirdly, you could also make two domains, one for eth0 and one for eth1 and restrict the interfaces in the XML config, and then create the Topics under the right participants.

Restricting at a Topic level which topic is allowed over which interface is not something I would want to support within a single participant. What DDS is about is that you can worry about the network topology while setting up your domains and configuration and then at application level you just publish and subscribe to your hearts content. DDS will figure out which data  has to go where and how to achieve that.

Lastly, thanks for your praise! Positive user feedback is all an open-source maintainer can dream off 😁. I'll be sure to share it with @eboasson, @dpotman, @reicheratwork and @hansvanthag. The increasing number of tickets on the python backend increases my workload but it really shows that more people are starting to use it. That makes working on this project all the more enjoyable!

**Comment by pscheie** [comment]
Hi @thijsmie,
After exploring your suggestions, I went with defining a separate domain for each NIC in my XML config.  The reason is eth1 is not expected to be physically connected at bootup but plugged in later, although the processes that publish and subscribe on that interface are started at bootup.  So, I was concerned that unless explicitly told to use eth1 they would default to eth0 when started since it is up from the beginning, which would not work for my needs.  Defining separate domains was easy enough, and also allowed me to fix a couple other issues.

Thanks for the help.
