### ISSUE TITLE
0.x Error on Ubuntu 22

### ISSUE THREAD

**Issue by NoeSechet** [eclipse-cyclonedds/cyclonedds-python#94]
Hi! 

is cyclone-python supported on Ubuntu 22? We manage to get cyclonedds as well as cyclonedds-cxx work on Ubuntu 22, but not the python one. 

Here is part of the output we get: 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
```

```
Traceback (most recent call last):
  File "/vehicle/publisher.py", line 16, in <module>
    from cyclonedds.core import Qos, Policy
ModuleNotFoundError: No module named 'cyclonedds'
Traceback (most recent call last):
  File "/vehicle/subscriber.py", line 13, in <module>
    from cyclonedds.core import Listener, WaitSet, ReadCondition, ViewState, SampleState, InstanceState, Qos, Policy
ModuleNotFoundError: No module named 'cyclonedds'
```

**Comment by thijsmie** [comment]
Hi there @NoeSechet!

I see no reason it wouldn't work, in fact, one of my development machines is running Ubuntu 22. The second trace suggests that the package is not actually installed. This can be for several reasons, one of which is that the install failed, as your other issue #95 suggests. If the install failed then the examples won't work, of course. If however this issue occurs with a different version you did manage to install, a common failure in python itself is that `pip` and `python` actually come from different python installations and confusing also daily python users like me. Try a `which pip` and `which python` to see that, or just give the install another go with `python -m pip install cyclonedds`.

If none of that works, could you post me the output of `python -m pip install --verbose cyclonedds` and `python -c "import sys;print(sys.path)"` to diagnose anything that might be wrong in the python setup on your machine or if something else funky is going on.

**Comment by thijsmie** [comment]
No more feedback received, closing and assuming it works now :innocent:.
